version: '3'

services:

    composer:
        image: composer
        volumes:
        - .:/app
        - composer-cache:/tmp

    bash:
        image: smartweb/php:7.1-fpm-dev
        entrypoint: 'bash'
        working_dir: '/app'
        volumes:
        - .:/app

volumes:
    composer-cache:
        driver: local
